# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_aws_eksa.metal as __metal
    metal = __metal
else:
    metal = _utilities.lazy_import('pulumi_aws_eksa.metal')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-eksa",
  "mod": "metal",
  "fqn": "pulumi_aws_eksa.metal",
  "classes": {
   "aws-eksa:metal:Cluster": "Cluster"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-eksa",
  "token": "pulumi:providers:aws-eksa",
  "fqn": "pulumi_aws_eksa",
  "class": "Provider"
 }
]
"""
)
